### ISSUE TITLE
[Feature Request] Configrable output format

### ISSUE THREAD

**Issue by CrazieIvan** [Ryan-rsm-McKenzie/CCExtender#4]
Hi Mr. Ryan,

I love using this mod with the nice filters you've made!

I only wish there was a way to turn off the new formatting scheme for the output, and use the vanilla format, which I sometimes find easier to read when outputting without filters. 

The vanilla output looks like this:
[FORM TYPE]: [FORM ID] [NAME]
![2021-05-16_110719](https://user-images.githubusercontent.com/69615600/118390489-fd0ee380-b637-11eb-958c-339c3cf74f71.jpg)

While the CCE format is: [plugin name] [FORM type]: [EDID] [FORM ID]
![2021-05-16_110548](https://user-images.githubusercontent.com/69615600/118390766-84108b80-b639-11eb-92d6-50812400c40a.jpg)

, which for me is more difficult to look at and sort through, because the most important field (FORM type) gets buried in a sea of text and it's in different positions inside the text, because of the varying plugin names at the beginning.  
I really like the added info like the plugin name and EDIT, but would it be possible to make the format configurable via a ini setting?

I appreciate you very much, and your work!  Thank you for reading this.

**Comment by Ryan-rsm-McKenzie** [comment]
You can filter on form type

**Comment by CrazieIvan** [comment]
Yes, and I do most of the time.   But sometimes I want to see all the existing form types in a search.  
I understand if you have no interest in this.  
A great mod nonetheless.  Thanks!

**Comment by Ryan-rsm-McKenzie** [comment]
It's not something I'm interested in adding

**Comment by CrazieIvan** [comment]
Alright, I appreciate the response!
